spring:
  application:
    name: payment
#  profiles:
#    active:
#      - jdbc
#      - vault
  config:
    import: "optional:configserver:http://ANHNT:ANHNT-PASS@localhost:7000/configuration/config"


  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"